---
- name: verify installation of the PHP-GD module
  package:
     name: php-gd
     state: present
  notify: Restart httpd

- name: Download Wordpress Archive
  get_url:
    url: http://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
 
- name: extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www
    copy: no

- name: Copy sample config file 
  command:
    mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

#- name: Find and replace in wp-config.php
#shell: sed -i -e 's/database_name_here/wordpress/g' -e 's/username_here/wordpress/g' -e 's/password_here/wordpress/g' /var/www/wordpress/wp-config.php
 
- name: Update WordPress config file
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp : "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'wordpress');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'wordpress');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'wordpress');"}

- name: Update DNS 
  shell:
    echo 172.22.150.176 awordpress.flo www.awordpress.flo >> /etc/hosts



